<?php
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->getTitle()) ?></td>
            <td><?= $this->escapeHtml($album->getArtist()) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?= $this->paginationControl(
        //Objeto paginator
        $this->paginator,
        //Estilo del scrolling
        'sliding',
        //El parcial a usar para renderizar el control.
        'partial/paginator',
        //La ruta para enlazar cuando un usuario 
        //hace clic en un enlace de control:
        ['route' => 'album']
    );
?>